---
# /*
#  * Copyright (c) 2021 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigateway.customPrefix" . }}{{ .Values.tcConfig }}
  labels:
    {{- include "apigateway.labels" . | nindent 4 }}
data:
  tc-config.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <con:tc-config xmlns:con="http://www.terracotta.org/config">
        <servers>
            {{- $fullSsName      := printf "%s%s" ( include "apigateway.customPrefix" . ) .Values.statefulsetName }}
            {{- $fullServiceName := printf "%s%s" ( include "apigateway.customPrefix" . ) .Values.serviceName }}
            <server host="{{ $fullSsName }}-0.{{ $fullServiceName }}" name="{{ $fullSsName }}-0" bind="0.0.0.0" jmx-enabled="false">
                <logs>stdout:</logs>
                <tsa-port bind="0.0.0.0">{{ .Values.port }}</tsa-port>
                <tsa-group-port bind="0.0.0.0">{{ .Values.syncPort }}</tsa-group-port>
            </server>
            <server host="{{ $fullSsName }}-1.{{ $fullServiceName }}" name="{{ $fullSsName }}-1" bind="0.0.0.0" jmx-enabled="false">
                <logs>/stdout:</logs>
                <tsa-port bind="0.0.0.0">{{ .Values.port }}</tsa-port>
                <tsa-group-port bind="0.0.0.0">{{ .Values.syncPort }}</tsa-group-port>
            </server>
            <client-reconnect-window>120</client-reconnect-window>
        </servers>
    </con:tc-config>
